### ISSUE TITLE
Comment About: Part 3: Migrating Gatsby Pages to TypeScript

### ISSUE THREAD

**Issue by rmcsharry** [assainov/extensive.one#1]
Fantastic work, great and detailed blog write up, thank you for doing this!

One error I found is in `templates/blog-post.tsx` where you import `INode` from `create-pages.tsx`, but in `create-pages.tsx` it is still called `IEdge`.

**Comment by assainov** [comment]
@rmcsharry Thanks for your feedback 👍 Hope it helped you!

**Comment by rmcsharry** [comment]
@assainov It was of enormous help, thanks.
