### ISSUE TITLE
Comment About: Introduction: Migrating Gatsby Site to TypeScript

### ISSUE THREAD

**Issue by stefanpl** [assainov/extensive.one#2]
Hey Ilyas, I just wanted to leave a huge **thank you** for your blog on migrating gatsby to TS! 
Since I'm a huge fan of TS, starting gatsby without it was out of the question … but the community support is indeed a bit lacking! I especially enjoyed the parts on using TS for the config files (via `require("ts-node").register();`, very neat!) and auto-generating interfaces for the queries. Quality stuff!

Keep up the great work :)

**Comment by assainov** [comment]
@stefanpl Thank you so much for your feedback! Amazing to know these articles help people.

I have just launched a YouTube channel, where I am planning to have more TypeScript - Gatsby - React content. Please check it out, and let me know if you are interested in specific topics/problems: https://www.youtube.com/channel/UCr8LXUSVTv7NgbL7m2f6RfQ
